name: generate-docs
on:
  push:
    branches:
      - master
jobs:
  generate-docs:
    name: generate-docs
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: ls
      - run: ls ../
      - uses: actions/checkout@v2
      - run: pwd
      - run: ls
      - run: ls ../